### ISSUE TITLE
Failure of the repo owner in teaching me DSA!!

### ISSUE THREAD

**Issue by YuZaGa** [um4ng-tiw/noob-boy-does-leetcode#1]
The issue was first encountered in 2020. Despite repeated attempts of me pleading to teach me DSA, no further action was taken. I think the system's broken.

**Comment by um4ng-tiw** [comment]
We understand the initial build had several issues and even after several patches it hasn't been solved. We can successfully conclude that the system is really broken.

**Comment by AryanFelix** [comment]
I agree with @YuZaGa. Very poor management by Repo owner. Expected better from Senpai. Kimochi Yameteee!

**Comment by um4ng-tiw** [comment]
@AryanFelix  - The repo owner just got Omae Wa Mou Shindaerud by pro devs. Time to leave coding.

**Comment by YuZaGa** [comment]
@AryanFelix Agreed. @um4ng-tiw Hence coming to the forgone conclusion that the issue won't be addressed, I am closing this issue. 🥺😭
